### ISSUE TITLE
Can't get this to run on a gpu

### ISSUE THREAD

**Issue by ogkalu2** [themrzmaster/git-re-basin-pytorch#6]
If I don't specify cpu when loading the models, I get

File review 
A = w_a @ w_b.T
"Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"

I now know the linear sum assignment message it can't ask run on a GPU but is it possible to get it to use both ?

**Comment by affableroots** [comment]
I'm no pytorch expert, but you can use `x.cpu()` to move something to the CPU, and then `x.cuda()` to move it back

**Comment by themrzmaster** [comment]
yea, just move everything to gpu, data and model.
